[project]
name = "ssts-backend"
version = "0.1.0"
description = "A face recognition based attendance api."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.2",
    "pathlib>=1.0.1",
    "psycopg2>=2.9.10",
    "python-dotenv>=1.1.1",
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "api/test"
]
python_files = [
    "*_test.py"
]
